//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManagementUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps.json.
        /// </summary>
        internal static string Apps_FileName {
            get {
                return ResourceManager.GetString("Apps_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://json.yevrag35.com/uimanagement-apps/v1.1.0/schema.json.
        /// </summary>
        internal static string Apps_SchemaUrl {
            get {
                return ResourceManager.GetString("Apps_SchemaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        internal static string ColumnHeaderName_Apps {
            get {
                return ResourceManager.GetString("ColumnHeaderName_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentHeader.
        /// </summary>
        internal static string ContentHeaderUid {
            get {
                return ResourceManager.GetString("ContentHeaderUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the credentials to start apps as:.
        /// </summary>
        internal static string CredBox_Content {
            get {
                return ResourceManager.GetString("CredBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunAs Credentials.
        /// </summary>
        internal static string CredBox_MainInstruction {
            get {
                return ResourceManager.GetString("CredBox_MainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUI.
        /// </summary>
        internal static string CredBox_Target {
            get {
                return ResourceManager.GetString("CredBox_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManagementUI RunAs.
        /// </summary>
        internal static string CredBox_WindowTitle {
            get {
                return ResourceManager.GetString("CredBox_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        internal static string NewApp_BtnContent_EDIT {
            get {
                return ResourceManager.GetString("NewApp_BtnContent_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string NewApp_DefaultButtonContent {
            get {
                return ResourceManager.GetString("NewApp_DefaultButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}....
        /// </summary>
        internal static string NewApp_Title_EDIT {
            get {
                return ResourceManager.GetString("NewApp_Title_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}{1}Are you sure you want to delete this app?.
        /// </summary>
        internal static string Prompt_AppDeleteContent {
            get {
                return ResourceManager.GetString("Prompt_AppDeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently Delete App.
        /// </summary>
        internal static string Prompt_AppDeleteMainInstruction {
            get {
                return ResourceManager.GetString("Prompt_AppDeleteMainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management UI.
        /// </summary>
        internal static string Prompt_AppDeleteTitle {
            get {
                return ResourceManager.GetString("Prompt_AppDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}{1}Are you you want to delete these tags?.
        /// </summary>
        internal static string Prompt_TagDeleteContent {
            get {
                return ResourceManager.GetString("Prompt_TagDeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Tag(s).
        /// </summary>
        internal static string Prompt_TagDeleteMainInstruction {
            get {
                return ResourceManager.GetString("Prompt_TagDeleteMainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management UI.
        /// </summary>
        internal static string Prompt_TagDeleteTitle {
            get {
                return ResourceManager.GetString("Prompt_TagDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notepad.
        /// </summary>
        internal static string Settings_DefaultEditor {
            get {
                return ResourceManager.GetString("Settings_DefaultEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://json.yevrag35.com/uimanagement/v1.1.0/schema.json.
        /// </summary>
        internal static string Settings_SchemaUrl {
            get {
                return ResourceManager.GetString("Settings_SchemaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1.
        /// </summary>
        internal static string Settings_Version {
            get {
                return ResourceManager.GetString("Settings_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.json.
        /// </summary>
        internal static string SettingsFileName {
            get {
                return ResourceManager.GetString("SettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings_debug.json.
        /// </summary>
        internal static string SettingsFileName_Debug {
            get {
                return ResourceManager.GetString("SettingsFileName_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %LOCALAPPDATA%\Mike Garvey\ManagementUI.
        /// </summary>
        internal static string SettingsPath {
            get {
                return ResourceManager.GetString("SettingsPath", resourceCulture);
            }
        }
    }
}
